const TYPES=[
["pizza","Pizza menu","A4","pizza"],["lunch","Lunch menu","A4","utensils"],["drinks","Drinks menu","A4","wine"],
["food","General food menu","A4","book-open"],["payments","Card & cash notice","A5 / A4","credit-card"],
["reserved","Reserved table sign","A5","calendar-check"],["garden","Garden rules","A4","trees"],
["toilet","Toilet notice","A5 / A4","info"],["qr","QR code sign","A5","qr-code"],
["event","Event poster","A4","party-popper"],["function","Function room hire","A4","building-2"],["custom","Custom sign","A4","file-pen-line"]
];
const NAV=[["overview","Overview","house"],["uploads","Upload & analyse","scan-search"],["copy","Approve wording","badge-check"],["studio","Pack preview","paintbrush"],["brand","Colours & theme","palette"],["selection","Add signs","panels-top-left"],["export","Export","download"]];
const DEMO_SIGNS={
 pizza:{title:"Pizza",subtitle:"Stone baked. Properly good.",copy:"CLASSICS\nMargherita | San Marzano tomato, mozzarella, basil | £11.50\nPepperoni | Tomato, mozzarella, pepperoni, honey | £12.50\nNduja & Honey | Nduja, chilli honey, rocket | £13.50\nWild Mushroom | Garlic béchamel, mushrooms, truffle oil | £12.95\n\nEXTRAS\nMixed leaf salad | | £3.00",exact:false},
 lunch:{title:"Lunch Menu",subtitle:"Served Monday to Friday, 12–3pm",copy:"MAINS\nFish & Chips | Beer battered cod, mushy peas, tartare sauce | £14.50\nSteak Sandwich | Caramelised onions, rocket, horseradish mayo | £13.50\nButternut Squash Risotto | Sage, parmesan, pumpkin seeds | £12.50\n\nSIDES\nSkinny fries | | £3.50\nHouse salad | | £3.50",exact:false},
 payments:{title:"A Quick Note",subtitle:"Card & cash payments",copy:"We’re happy to accept both card and cash payments.\n\nPlease ask a member of the team if you need any help.",exact:true},
 reserved:{title:"Reserved",subtitle:"We look forward to welcoming you",copy:"For:\n\nAt:",exact:true}
};
const DEFAULT={id:"demo-pub",venueName:"The Crown & Anchor",venueType:"traditional pub",location:"Yorkshire",brandStyle:"traditional",primaryColor:"#79252c",secondaryColor:"#fffdf8",textColor:"#252525",accentColor:"#b78a38",typography:"classic serif",tone:"warm",notes:"A welcoming village pub known for stone-baked pizzas, proper lunches and friendly service.",avoid:"Corporate language, clutter, aggressive policy wording.",exactWording:"Please inform our team of any allergies.",borderStyle:"thin decorative",iconStyle:"classic line",layoutDensity:"comfortable",styleFamily:"traditional",selectedSigns:["pizza","lunch","payments","reserved"],signs:structuredClone(DEMO_SIGNS),uploads:[],aiStatus:"demo",aiSummary:"Warm, traditional village pub with polished but friendly wording.",checks:{spelling:true,prices:true,dates:false,times:false,policy:true,logo:true,size:true}};
const RECENT=[["Summer Menu Pack","4 signs","Copy reviewed","review","Today, 2:15 pm"],["Live Music Friday A3","1 sign","Draft","draft","Today, 11:08 am"],["Sunday Roast Specials","3 signs","Design complete","complete","Yesterday, 4:42 pm"],["Cocktail Menu Refresh","5 signs","Draft","draft","Yesterday, 10:31 am"],["Quiz Night A4","1 sign","Copy reviewed","review","20 May 2026"],["Christmas Party Promo","2 signs","Archived","archived","18 May 2026"]];
let jobs=load(),job=jobs.find(x=>x.id==="demo-pub")||structuredClone(DEFAULT),page="overview",active=job.selectedSigns[0]||"pizza",analysing=false;
job.aiStatus=job.aiStatus||"not-run";job.aiSummary=job.aiSummary||"";Object.values(job.signs||{}).forEach(s=>{s.originalCopy=s.originalCopy||s.copy;s.suggestedCopy=s.suggestedCopy||s.copy;s.approval=s.approval||"original";s.flags=s.flags||[]});
function load(){try{return JSON.parse(localStorage.getItem("pub-sign-pack-jobs"))||[structuredClone(DEFAULT)]}catch{return[structuredClone(DEFAULT)]}}
function save(){let i=jobs.findIndex(x=>x.id===job.id);if(i<0)jobs.unshift(job);else jobs[i]=job;localStorage.setItem("pub-sign-pack-jobs",JSON.stringify(jobs))}
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const ico=(n,s=20)=>`<i data-lucide="${n}" style="width:${s}px;height:${s}px"></i>`;
const slug=v=>String(v||"venue").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const initials=v=>String(v||"PS").replace(/^the\s+/i,"").split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase();
function icons(){lucide?.createIcons({attrs:{"stroke-width":1.8}})}
function toast(t){let e=document.querySelector("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2200)}
function meta(id){return TYPES.find(x=>x[0]===id)||TYPES[0]}
function sign(id){if(!job.signs[id])job.signs[id]={title:meta(id)[1],subtitle:"Add a short supporting line",originalCopy:"Needs checking",suggestedCopy:"Needs checking",copy:"Needs checking",approval:"original",flags:[],exact:false};return job.signs[id]}
function render(){document.querySelector("#app").innerHTML=`<div class="shell">${sidebar()}<main class="main"><header class="topbar"><button class="mobile" data-menu>${ico("menu")} Menu</button><button>${ico("bell")} Notifications</button><button>${ico("circle-user-round")} My account</button></header><div class="content">${content()}</div></main></div>`;bind();icons()}
function sidebar(){return`<aside class="sidebar" id="sidebar"><div class="brand">${ico("crown",30)}<b>PUB SIGN</b><span>PACK BUILDER</span><div class="rule"></div></div><nav class="nav">${NAV.map(x=>`<button class="${page===x[0]?"on":""}" data-page="${x[0]}">${ico(x[2])}${x[1]}</button>`).join("")}</nav><div class="spacer"></div><div class="sidefoot"><button class="nav" data-reset>${ico("settings")} Reset demo</button><div class="venue"><span class="avatar">${initials(job.venueName)}</span><span>${esc(job.venueName)}</span></div></div></aside>`}
function heading(k,t,s,a=""){return`<div class="heading"><div><p class="eyebrow">${k}</p><h1>${t}</h1><p class="sub">${s}</p></div>${a}</div>`}
function content(){return page==="overview"?overview():page==="brand"?brand():page==="uploads"?uploads():page==="selection"?selection():page==="copy"?copy():page==="studio"?studio():exports()}
function overview(){return`<div class="overview"><section><div class="hero"><p class="eyebrow">Fast sign tidy-up</p><h1>Upload old signs.<br>Get a branded pack.</h1><p class="sub">AI reads the wording, works out the venue style and prepares improvements for your approval.</p><button class="primary" data-page="uploads">${ico("scan-search")} Upload signs & build pack</button><div class="fastpath">${[["1. Upload","Photos, menus, PDFs and logo"],["2. AI reads","Brand, wording and sign types"],["3. Approve","Keep original or accept changes"],["4. Export","A consistent PDF and ZIP pack"]].map(x=>`<div class="faststep"><b>${x[0]}</b><span>${x[1]}</span></div>`).join("")}</div></div><div class="section"><div class="section-head"><div class="section-title">Recent jobs</div><button class="textbtn">View all jobs →</button></div><div class="table"><div class="row head"><span>JOB NAME</span><span>SIGNS</span><span>STATUS</span><span>UPDATED</span><span></span></div>${RECENT.map(x=>`<div class="row"><span>${x[0]}</span><span>${x[1]}</span><span class="status ${x[3]}">${x[2]}</span><span>${x[4]}</span><span>•••</span></div>`).join("")}</div></div></section><section>${preview("pizza",1)}</section></div>`}
const field=(id,l,type="text")=>`<label>${l}<input type="${type}" data-field="${id}" class="${type==="color"?"color":""}" value="${esc(job[id])}"></label>`;
const area=(id,l)=>`<label class="full">${l}<textarea data-field="${id}">${esc(job[id])}</textarea></label>`;
function select(id,l,opts){return`<label>${l}<select data-field="${id}">${opts.map(x=>`<option ${job[id]===x?"selected":""}>${x}</option>`).join("")}</select></label>`}
function brand(){return`${heading("Step 1 of 6","Brand & venue","Set the rules once, then keep every sign consistent.",`<button class="primary" data-next="uploads">Save & continue ${ico("arrow-right")}</button>`)}<div class="workspace"><section><div class="formsection"><h3>Venue details</h3><p class="help">The basics used throughout the pack.</p><div class="grid">${field("venueName","Venue name")}${select("venueType","Venue type",["traditional pub","gastropub","sports bar","cocktail bar","cafe","restaurant"])}${field("location","Town / location")}${select("brandStyle","Brand style",["traditional","premium","rustic","modern","playful","bold","classic"])}</div></div><div class="formsection"><h3>Brand palette</h3><div class="grid">${field("primaryColor","Primary colour","color")}${field("secondaryColor","Secondary colour","color")}${field("textColor","Text colour","color")}${field("accentColor","Accent colour","color")}</div></div><div class="formsection"><h3>Voice & direction</h3><div class="grid">${select("typography","Typography feel",["classic serif","clean modern","rustic","bold pub style"])}${select("tone","Tone of voice",["warm","friendly","premium","clear","playful","direct"])}${area("notes","Notes about the venue")}${area("avoid","Anything to avoid")}${area("exactWording","Exact wording that must not change")}</div></div></section><section>${preview(active)}</section></div>`}
function uploads(){let configured=!!window.PUB_SIGN_API_URL;return`${heading("Step 1","Upload the current signs","Add the scruffy originals, menus, logo and a couple of venue photos.",``)}<div class="drop" id="drop">${ico("cloud-upload",34)}<h3>Drop everything we should learn from</h3><p class="help">Clear photos work best. PNG, JPG, SVG and PDF are accepted.</p><button class="secondary" data-browse>${ico("folder-open")} Choose files</button><input id="files" type="file" multiple accept="image/*,.pdf,.svg"></div><div class="assets">${job.uploads.length?job.uploads.map((f,i)=>`<div class="asset"><div class="thumb">${f.data?.startsWith("data:image")?`<img src="${f.data}" alt="">`:ico(f.type.includes("pdf")?"file-text":"image",30)}</div><div class="filename">${esc(f.name)}</div><div class="filetype">${esc(f.type||"file")} · <button class="textbtn" data-remove="${i}">Remove</button></div></div>`).join(""):`<div class="empty full">${ico("images",38)}<p>Upload at least one sign or menu image.</p></div>`}</div><div class="ai-bar"><div><b>Analyse brand, extract wording and build the pack</b><p>Prices, dates, opening times, policies and legal wording are preserved or flagged, never invented.</p></div><button class="primary" data-analyse ${analysing||!job.uploads.length?"disabled":""}>${analysing?ico("loader-circle",18)+" Analysing…":ico("sparkles")+" Analyse & build pack"}</button></div>${job.aiSummary?brandReadout():""}<div class="api-note">${configured?"Secure AI endpoint connected.":"Preview mode: the workflow is live, but real image reading needs the included secure worker to be deployed and connected."}</div>`}
function selection(){return`${heading("Step 3 of 6","Choose your signs","Start with what you need today. You can change this later.",`<button class="primary" data-next="copy">Review copy ${ico("arrow-right")}</button>`)}<div class="signgrid">${TYPES.map(x=>`<button class="signchoice ${job.selectedSigns.includes(x[0])?"selected":""}" data-choice="${x[0]}"><span class="checkmark">${ico("check")}</span>${ico(x[3])}<b>${x[1]}</b><span>${x[2]} portrait</span></button>`).join("")}</div>`}
function tabs(){return`<div class="tabs">${job.selectedSigns.map(id=>`<button class="tab ${active===id?"on":""}" data-active="${id}">${meta(id)[1]}</button>`).join("")}</div>`}
function copy(){if(!job.selectedSigns.length)return`${heading("Step 2","Approve wording","Analyse uploads or add at least one sign first.")}<div class="empty"><button class="primary" data-page="uploads">Upload signs</button></div>`;let s=sign(active),original=s.originalCopy||s.copy,suggested=s.suggestedCopy||s.copy;return`${heading("Step 2","Approve the wording","Keep the original, use the AI suggestion, or edit either before building the pack.",`<button class="primary" data-next="studio">Build pack ${ico("arrow-right")}</button>`)}<div class="workspace"><section>${tabs()}<div class="warning">${ico("triangle-alert")}<span><b>You approve every change.</b><br>Check spelling, prices, dates, opening times, policy and legal wording before export.</span></div><div class="compare"><div class="copybox"><h3>Extracted original</h3><pre>${esc(original)}</pre></div><div class="copybox suggested"><h3>Suggested improvement</h3><pre>${esc(suggested)}</pre></div></div>${(s.flags||[]).map(x=>`<span class="flag">${ico("triangle-alert",11)}${esc(x)}</span>`).join("")}<div class="approval"><button class="secondary ${s.approval==="original"?"on":""}" data-approve="original">${ico("lock",15)} Keep original</button><button class="secondary ${s.approval==="suggested"?"on":""}" data-approve="suggested">${ico("sparkles",15)} Use suggestion</button><button class="secondary ${s.approval==="edited"?"on":""}" data-approve="edited">${ico("pencil-line",15)} Use edited copy</button></div><div class="grid"><label>Sign title<input data-sfield="title" value="${esc(s.title)}"></label><label>Supporting line<input data-sfield="subtitle" value="${esc(s.subtitle)}"></label><label class="full">Approved / edited wording<textarea data-sfield="copy" style="min-height:230px">${esc(s.copy)}</textarea></label></div></section><section>${preview(active)}</section></div>`}
function studio(){if(!job.selectedSigns.length)return copy();return`${heading("Step 5 of 6","Design studio","Switch styles without losing your venue colours or approved wording.",`<button class="primary" data-next="export">Review export ${ico("arrow-right")}</button>`)}<div class="workspace"><section>${tabs()}<div class="styles">${[["traditional","Traditional Pub"],["modern","Modern Clean"],["rustic","Rustic Gastropub"]].map(x=>`<button class="style ${job.styleFamily===x[0]?"on":""}" data-style="${x[0]}">${x[1]}</button>`).join("")}</div><div class="formsection"><h3>Shared brand tokens</h3><p class="help">Applied across all ${job.selectedSigns.length} signs.</p><div class="table">${[["Venue",job.venueName],["Heading",job.typography],["Tone",job.tone],["Border",job.borderStyle],["Layout",job.layoutDensity],["Logo",job.uploads.find(x=>x.type.includes("image"))?.name||"Venue name masthead"]].map(x=>`<div class="row" style="grid-template-columns:1fr 1fr"><b>${x[0]}</b><span>${esc(x[1])}</span></div>`).join("")}</div></div><div class="actions"><button class="secondary" data-page="copy">${ico("pencil-line")} Edit wording</button><button class="primary" data-regen>${ico("refresh-cw")} Regenerate draft</button></div></section><section>${preview(active)}</section></div>`}
function exports(){let ready=Object.values(job.checks).every(Boolean);return`${heading("Step 6 of 6","Ready for the printer?","Complete the checks to remove the draft watermark.")}<div class="workspace"><section><div class="formsection"><h3>Pre-export checklist</h3><p class="help">Draft exports are always available.</p><div class="checklist">${[["spelling","Spelling checked"],["prices","Prices checked"],["dates","Dates checked"],["times","Opening times checked"],["policy","Policy wording checked"],["logo","Logo correct"],["size","Print size correct"]].map(x=>`<label class="checkline"><input type="checkbox" data-check="${x[0]}" ${job.checks[x[0]]?"checked":""}>${x[1]}</label>`).join("")}</div></div><div class="exports"><div class="export">${ico("file-down")}<div><b>Selected sign PDF</b><span>${meta(active)[1]} · ${ready?"Final":"Draft watermarked"}</span></div><button class="secondary small" data-pdf>Export</button></div><div class="export">${ico("files")}<div><b>Combined pack PDF</b><span>${job.selectedSigns.length} signs in one file</span></div><button class="secondary small" data-all>Export</button></div><div class="export">${ico("archive")}<div><b>Full ZIP pack</b><span>PDFs, preview PNGs, brief, copy and notes</span></div><button class="primary small" data-zip>Download</button></div></div><p class="help">${ready?"All checks complete. Final exports have no watermark.":"Incomplete checks mean exports show “DRAFT - CHECK BEFORE PRINT”."}</p></section><section>${preview(active)}</section></div>`}
function preview(id,overview=0){let s=sign(id),m=meta(id),ready=Object.values(job.checks).every(Boolean);return`<div class="previewwrap"><div class="paper ${job.styleFamily}" style="--pp:${job.primaryColor};--pa:${job.accentColor};--pt:${job.textColor};background:${job.secondaryColor}"><div class="paperin"><div class="plogo"><div class="plogomark">${initials(job.venueName)}</div>${esc(job.venueName)}</div>${previewBody(id,s)}${ready?"":`<div class="watermark">DRAFT - CHECK BEFORE PRINT</div>`}</div></div><div class="meta"><span>${ico("info",13)} ${m[2].startsWith("A5")?"A5":"A4"} portrait · print-safe</span>${overview?`<button class="secondary small" data-page="studio">View in studio</button>`:`<span>${job.styleFamily}</span>`}</div></div>`}
function previewBody(id,s){if(id==="reserved")return`<div class="reserved">${esc(s.title)}</div>${s.copy.split("\n").filter(Boolean).map(x=>`<div class="reservedline">${esc(x)}</div>`).join("")}<div class="flourish">◆</div>`;if(["payments","garden","toilet","qr","event","function","custom"].includes(id))return`<div class="ptitle" style="font-size:35px;letter-spacing:.05em">${esc(s.title)}</div><div class="pkicker">${esc(s.subtitle)}</div><div class="flourish">◆</div><div class="notice">${esc(s.copy)}</div>`;return`<div class="ptitle">${esc(s.title)}</div><div class="pkicker">${esc(s.subtitle)}</div><div class="flourish">◆</div>${parseMenu(s.copy).map(sec=>`<div class="menusection"><div class="menutitle">${esc(sec.title)}</div>${sec.items.map(x=>`<div class="menuitem"><div class="menuhead"><span>${esc(x.name)}</span><span class="dots"></span><span>${esc(x.price)}</span></div>${x.desc?`<div class="desc">${esc(x.desc)}</div>`:""}</div>`).join("")}</div>`).join("")}`}
function parseMenu(copy){let out=[],cur={title:"Menu",items:[]};String(copy||"").split("\n").forEach(raw=>{let l=raw.trim();if(!l)return;if(!l.includes("|")&&l.length<30){if(cur.items.length)out.push(cur);cur={title:l,items:[]}}else{let[name="",desc="",price=""]=l.split("|").map(x=>x.trim());cur.items.push({name,desc,price})}});if(cur.items.length||!out.length)out.push(cur);return out.slice(0,4)}
function brandReadout(){return`<div class="ai-state ready">${ico("circle-check",16)} Analysis ready · ${esc(job.aiSummary)}</div><div class="brandread">${[["Brand feel",job.brandStyle],["Tone",job.tone],["Typography",job.typography],["Signs found",job.selectedSigns.length]].map(x=>`<div><b>${esc(x[1])}</b><span>${x[0]}</span></div>`).join("")}</div><button class="primary" data-page="copy">Approve wording ${ico("arrow-right")}</button>`}
function bind(){
 document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page));
 document.querySelector("[data-menu]")?.addEventListener("click",()=>document.querySelector("#sidebar").classList.toggle("open"));
 document.querySelector("[data-reset]")?.addEventListener("click",()=>{if(confirm("Reset the demo job?")){job=structuredClone(DEFAULT);jobs=[job];active="pizza";page="overview";save();render()}});
 document.querySelector("[data-new]")?.addEventListener("click",()=>{job=structuredClone(DEFAULT);job.id="job-"+Date.now();job.venueName="New venue";job.location="";job.uploads=[];job.selectedSigns=[];job.signs={};Object.keys(job.checks).forEach(k=>job.checks[k]=false);jobs.unshift(job);save();go("brand")});
 document.querySelectorAll("[data-next]").forEach(b=>b.onclick=()=>{save();go(b.dataset.next)});
 document.querySelectorAll("[data-field]").forEach(e=>e.oninput=()=>{job[e.dataset.field]=e.value;save();if(e.type==="color")render()});
 document.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{let id=b.dataset.choice;if(job.selectedSigns.includes(id))job.selectedSigns=job.selectedSigns.filter(x=>x!==id);else{job.selectedSigns.push(id);sign(id)}if(!job.selectedSigns.includes(active))active=job.selectedSigns[0]||"pizza";save();render()});
 document.querySelectorAll("[data-active]").forEach(b=>b.onclick=()=>{active=b.dataset.active;render()});
 document.querySelectorAll("[data-sfield]").forEach(e=>e.oninput=()=>{let s=sign(active);s[e.dataset.sfield]=e.value;if(e.dataset.sfield==="copy")s.approval="edited";save();replacePreview()});
 document.querySelector("[data-exact]")?.addEventListener("click",()=>{sign(active).exact=!sign(active).exact;save();render()});
 document.querySelector("[data-tidy]")?.addEventListener("click",()=>{if(sign(active).exact)return toast("Exact wording is protected");sign(active).copy=sign(active).copy.replace(/\s+\n/g,"\n").replace(/\n{3,}/g,"\n\n").replace(/\bpls\b/gi,"Please").trim();save();render();toast("Copy tidied without changing prices")});
 document.querySelectorAll("[data-style]").forEach(b=>b.onclick=()=>{job.styleFamily=b.dataset.style;save();render()});
 document.querySelector("[data-regen]")?.addEventListener("click",()=>{render();toast("Fresh branded draft generated")});
 document.querySelectorAll("[data-check]").forEach(e=>e.onchange=()=>{job.checks[e.dataset.check]=e.checked;save();render()});
 document.querySelector("[data-browse]")?.addEventListener("click",()=>document.querySelector("#files").click());
 document.querySelector("[data-analyse]")?.addEventListener("click",analyseUploads);
 document.querySelector("#files")?.addEventListener("change",e=>addFiles(e.target.files));
 document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{job.uploads.splice(+b.dataset.remove,1);save();render()});
 let d=document.querySelector("#drop");if(d){["dragenter","dragover"].forEach(n=>d.addEventListener(n,e=>{e.preventDefault();d.classList.add("drag")}));["dragleave","drop"].forEach(n=>d.addEventListener(n,e=>{e.preventDefault();d.classList.remove("drag")}));d.addEventListener("drop",e=>addFiles(e.dataTransfer.files))}
 document.querySelector("[data-pdf]")?.addEventListener("click",()=>exportPdf([active]));
 document.querySelector("[data-all]")?.addEventListener("click",()=>exportPdf(job.selectedSigns,1));
 document.querySelector("[data-zip]")?.addEventListener("click",exportZip);
 document.querySelectorAll("[data-approve]").forEach(b=>b.onclick=()=>approveCopy(b.dataset.approve));
}
function go(p){page=p;document.querySelector("#sidebar")?.classList.remove("open");render();scrollTo({top:0,behavior:"smooth"})}
function replacePreview(){let old=document.querySelector(".previewwrap");if(!old)return;let box=document.createElement("div");box.innerHTML=preview(active);old.replaceWith(box.firstElementChild);icons()}
function addFiles(files){[...files].forEach(f=>{let r=new FileReader;r.onload=()=>{job.uploads.push({name:f.name,type:f.type||"file",size:f.size,data:f.size<1500000?r.result:""});save();render()};r.readAsDataURL(f)})}
function approveCopy(mode){let s=sign(active);s.approval=mode;if(mode==="original")s.copy=s.originalCopy||s.copy;if(mode==="suggested")s.copy=s.suggestedCopy||s.copy;save();render();toast(mode==="suggested"?"Suggestion approved":"Original wording kept")}
async function analyseUploads(){
 analysing=true;render();
 try{
  let result=window.PUB_SIGN_API_URL?await callAiWorker():demoAnalysis();
  applyAnalysis(result);job.aiStatus=window.PUB_SIGN_API_URL?"complete":"preview";save();analysing=false;render();toast("Brand read and sign pack prepared");
 }catch(error){analysing=false;job.aiStatus="error";render();toast(error.message||"Analysis failed")}
}
async function callAiWorker(){
 let files=job.uploads.filter(x=>x.data).slice(0,12).map(x=>({name:x.name,type:x.type,dataUrl:x.data}));
 let response=await fetch(window.PUB_SIGN_API_URL.replace(/\/$/,"")+"/analyse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({files,venueHint:job.venueName==="New venue"?"":job.venueName,notes:job.notes||""})});
 if(!response.ok)throw new Error((await response.json().catch(()=>({}))).error||"AI analysis failed");
 return response.json()
}
function demoAnalysis(){
 let names=job.uploads.map(x=>x.name.toLowerCase()).join(" ");
 let detected=names.includes("lunch")?["lunch"]:names.includes("pizza")?["pizza"]:["pizza","lunch","payments"];
 return{brand:{venueName:job.venueName==="New venue"?"Needs checking":job.venueName,venueType:"traditional pub",brandStyle:"traditional",tone:"warm and friendly",typography:"classic serif",primaryColor:"#79252c",secondaryColor:"#fffdf8",textColor:"#252525",accentColor:"#b78a38",summary:"Warm independent pub brand with classic typography and direct, friendly language."},signs:detected.map(id=>{let base=structuredClone(DEMO_SIGNS[id]||{title:meta(id)[1],subtitle:"Needs checking",copy:"Needs checking"});return{id,title:base.title,subtitle:base.subtitle,originalCopy:base.copy,suggestedCopy:base.copy.replace("We’re happy to","We’re pleased to"),flags:["Preview result — connect the secure AI worker for real image reading"]}})}
}
function applyAnalysis(result){
 let b=result.brand||{};["venueName","venueType","brandStyle","tone","typography","primaryColor","secondaryColor","textColor","accentColor"].forEach(k=>{if(b[k])job[k]=b[k]});job.aiSummary=b.summary||"Brand and wording extracted from uploads.";job.selectedSigns=[];job.signs={};
 (result.signs||[]).forEach((item,i)=>{let id=TYPES.some(x=>x[0]===item.id)?item.id:(i?"custom":"food");if(job.selectedSigns.includes(id))id="custom";job.selectedSigns.push(id);job.signs[id]={title:item.title||meta(id)[1],subtitle:item.subtitle||"",originalCopy:item.originalCopy||"Needs checking",suggestedCopy:item.suggestedCopy||item.originalCopy||"Needs checking",copy:item.originalCopy||"Needs checking",approval:"original",exact:false,flags:item.flags||[]}});
 if(!job.selectedSigns.length){job.selectedSigns=["custom"];sign("custom")}active=job.selectedSigns[0]
}
const trim=(t,n)=>String(t||"").length>n?String(t).slice(0,n-1)+"…":String(t||"");
function wrap(text,n=65){let out=[];String(text||"").split("\n").forEach(p=>{if(!p){out.push("");return}let line="";p.split(/\s+/).forEach(w=>{if((line+" "+w).trim().length>n){out.push(line);line=w}else line=(line+" "+w).trim()});if(line)out.push(line)});return out}
function rgb(hex){let h=hex.replace("#","");return[parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255]}
function centered(p,text,y,size,font,width,color){let t=String(text||""),w=font.widthOfTextAtSize(t,size);p.drawText(t,{x:Math.max(30,(width-w)/2),y,size,font,color})}
async function makePdf(ids){
 const{PDFDocument,StandardFonts,rgb:R}=PDFLib,doc=await PDFDocument.create(),regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),serif=await doc.embedFont(StandardFonts.TimesRoman),serifBold=await doc.embedFont(StandardFonts.TimesRomanBold),ready=Object.values(job.checks).every(Boolean),pc=rgb(job.primaryColor),ac=rgb(job.accentColor);
 ids.forEach(id=>{let s=sign(id),m=meta(id),a5=m[2].startsWith("A5"),size=a5?[419.53,595.28]:[595.28,841.89],p=doc.addPage(size),[w,h]=size;
 p.drawRectangle({x:22,y:22,width:w-44,height:h-44,borderWidth:1.6,borderColor:R(...pc)});p.drawRectangle({x:29,y:29,width:w-58,height:h-58,borderWidth:.6,borderColor:R(...ac)});
 centered(p,job.venueName.toUpperCase(),h-68,12,bold,w,R(...pc));centered(p,s.title.toUpperCase(),h-126,a5?29:41,serifBold,w,R(...pc));centered(p,s.subtitle,h-151,10,regular,w,R(...ac));p.drawLine({start:{x:w*.38,y:h-171},end:{x:w*.62,y:h-171},thickness:1,color:R(...ac)});
 let y=h-205;if(["pizza","lunch","drinks","food"].includes(id))parseMenu(s.copy).forEach(sec=>{if(y<90)return;centered(p,sec.title.toUpperCase(),y,11,bold,w,R(...pc));y-=22;sec.items.forEach(x=>{if(y<65)return;p.drawText(trim(x.name,45),{x:55,y,size:11,font:serifBold});let pw=serifBold.widthOfTextAtSize(x.price,11);p.drawText(x.price,{x:w-55-pw,y,size:11,font:serifBold});y-=13;if(x.desc){p.drawText(trim(x.desc,78),{x:55,y,size:8.5,font:serif});y-=13}y-=7});y-=8});else wrap(s.copy,62).forEach(line=>{if(y<75)return;centered(p,line,y,13,serif,w,R(.16,.16,.16));y-=21});
 if(job.exactWording)centered(p,trim(job.exactWording,70),47,7,regular,w,R(.3,.3,.3));if(!ready)centered(p,"DRAFT - CHECK BEFORE PRINT",34,8,bold,w,R(.55,.12,.14))
 });return doc.save()
}
function download(blob,name){let u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),4000)}
function pdfName(id){let m=meta(id);return`${slug(job.venueName)}_${slug(m[1])}_${m[2].startsWith("A5")?"A5":"A4"}.pdf`}
async function exportPdf(ids,all=0){toast("Preparing PDF…");let bytes=await makePdf(ids);download(new Blob([bytes],{type:"application/pdf"}),all?`${slug(job.venueName)}_full-sign-pack.pdf`:pdfName(ids[0]));toast("PDF ready")}
function previewPng(id){return new Promise(resolve=>{let c=document.createElement("canvas");c.width=794;c.height=1123;let x=c.getContext("2d"),s=sign(id);x.fillStyle=job.secondaryColor;x.fillRect(0,0,c.width,c.height);x.strokeStyle=job.primaryColor;x.lineWidth=4;x.strokeRect(35,35,c.width-70,c.height-70);x.strokeStyle=job.accentColor;x.lineWidth=1;x.strokeRect(48,48,c.width-96,c.height-96);x.textAlign="center";x.fillStyle=job.primaryColor;x.font="bold 23px Georgia";x.fillText(job.venueName.toUpperCase(),397,105);x.font="bold 60px Georgia";x.fillText(s.title.toUpperCase(),397,205);x.fillStyle=job.accentColor;x.font="18px Georgia";x.fillText(s.subtitle,397,242);x.fillStyle=job.textColor;x.textAlign="left";let y=305;wrap(s.copy.replace(/\|/g,"  "),62).slice(0,30).forEach(l=>{x.font=/^[A-Z &]+$/.test(l)?"bold 22px Georgia":"18px Georgia";x.fillText(l,85,y);y+=/^[A-Z &]+$/.test(l)?38:29});if(!Object.values(job.checks).every(Boolean)){x.fillStyle="#8a252b";x.textAlign="center";x.font="bold 15px Arial";x.fillText("DRAFT - CHECK BEFORE PRINT",397,1080)}c.toBlob(resolve,"image/png")})}
async function exportZip(){
 toast("Building full sign pack…");let z=new JSZip,pdfs=z.folder("final-pdfs"),pngs=z.folder("preview-pngs");
 for(let id of job.selectedSigns){pdfs.file(pdfName(id),await makePdf([id]));pngs.file(pdfName(id).replace(".pdf",".png"),await previewPng(id))}
 pdfs.file(`${slug(job.venueName)}_full-sign-pack.pdf`,await makePdf(job.selectedSigns));
 z.file("brand-brief.json",JSON.stringify({venueName:job.venueName,venueType:job.venueType,location:job.location,primaryColor:job.primaryColor,secondaryColor:job.secondaryColor,textColor:job.textColor,accentColor:job.accentColor,headingFont:job.typography,bodyFont:"DM Sans",borderStyle:job.borderStyle,iconStyle:job.iconStyle,layoutDensity:job.layoutDensity,toneOfVoice:job.tone,logoPath:job.uploads.find(x=>x.type.includes("image"))?.name||null},null,2));
 z.file("copy-used.txt",job.selectedSigns.map(id=>`${sign(id).title.toUpperCase()}\n${sign(id).subtitle}\n\n${sign(id).copy}`).join("\n\n--------------------\n\n"));
 z.file("README.txt",`PUB SIGN PACK BUILDER\n${job.venueName}\n\nPrint at actual size / 100% scaling.\nCheck spelling, prices, dates, times, policies and allergy information.\nDraft files include a watermark until every quality check is complete.\nAsk your printer to confirm bleed and colour requirements.\n`);
 download(await z.generateAsync({type:"blob"}),`${slug(job.venueName)}_sign-pack.zip`);toast("ZIP pack ready")
}
render();
